# Generated by Django 3.2.8 on 2021-10-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lote', models.PositiveSmallIntegerField(verbose_name='Lote')),
                ('valor_x', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Medida Eixo X')),
                ('valor_y', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Medida Eixo Y')),
                ('data', models.DateField(auto_now=True, verbose_name='Data')),
                ('horario', models.TimeField(auto_now=True, verbose_name='Horário')),
            ],
        ),
    ]
