# Generated by Django 3.2.8 on 2021-11-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livevideo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calibracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
                ('n_amostra', models.PositiveSmallIntegerField(verbose_name='N° de Amostras')),
                ('val_x1', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Medida 1 Eixo X')),
                ('val_y1', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Medida 2 Eixo Y')),
                ('val_x2', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Medida 2 Eixo X')),
                ('val_y2', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Medida 2 Eixo Y')),
                ('val_x3', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Medida 3 Eixo X')),
                ('val_y3', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Medida 3 Eixo Y')),
                ('val_x4', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Medida 4 Eixo X')),
                ('val_y4', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Medida 4 Eixo Y')),
                ('val_x5', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Medida 5 Eixo X')),
                ('val_y5', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Medida 5 Eixo Y')),
                ('val_x6', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Medida 5 Eixo X')),
                ('val_y6', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Medida 5 Eixo Y')),
                ('val_x7', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Medida 5 Eixo X')),
                ('val_y7', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Medida 5 Eixo Y')),
                ('val_x8', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Medida 5 Eixo X')),
                ('val_y8', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Medida 5 Eixo Y')),
                ('val_x9', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Medida 5 Eixo X')),
                ('val_y9', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Medida 5 Eixo Y')),
            ],
        ),
    ]
