# Generated by Django 3.2.8 on 2021-11-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livevideo', '0002_calibracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibracao',
            name='val_x6',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Medida 6 Eixo X'),
        ),
        migrations.AlterField(
            model_name='calibracao',
            name='val_x7',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Medida 7 Eixo X'),
        ),
        migrations.AlterField(
            model_name='calibracao',
            name='val_x8',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Medida 8 Eixo X'),
        ),
        migrations.AlterField(
            model_name='calibracao',
            name='val_x9',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Medida 9 Eixo X'),
        ),
        migrations.AlterField(
            model_name='calibracao',
            name='val_y6',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Medida 6 Eixo Y'),
        ),
        migrations.AlterField(
            model_name='calibracao',
            name='val_y7',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Medida 7 Eixo Y'),
        ),
        migrations.AlterField(
            model_name='calibracao',
            name='val_y8',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Medida 8 Eixo Y'),
        ),
        migrations.AlterField(
            model_name='calibracao',
            name='val_y9',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Medida 9 Eixo Y'),
        ),
    ]
