# Generated by Django 3.2.8 on 2021-11-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livevideo', '0003_auto_20211102_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibracao',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
